name: quiz_app_pdp
description: "This is quiz application with PDP Academy"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  d_navigation_bar: ^0.0.1
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  pinput: ^4.0.0
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lottie/
    - assets/fonts/

  fonts:
    - family: "Poppins"
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
