// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWuLvbiYNIDgQZjYVQCMj4jgGZPZTacyc',
    appId: '1:614160463111:web:608f56b9ff06d6a588c1a2',
    messagingSenderId: '614160463111',
    projectId: 'quiz-app-pdp',
    authDomain: 'quiz-app-pdp.firebaseapp.com',
    storageBucket: 'quiz-app-pdp.appspot.com',
    measurementId: 'G-32ES9FMNK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdH9YXN6gmXl4VksL6tI1p1AVUwI_MknA',
    appId: '1:614160463111:android:66d8a1a39a16d7a488c1a2',
    messagingSenderId: '614160463111',
    projectId: 'quiz-app-pdp',
    storageBucket: 'quiz-app-pdp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMnkIeY-Ey-BchANeu7xIH2_kZoKFdgpI',
    appId: '1:614160463111:ios:5c99529aef4a4f0088c1a2',
    messagingSenderId: '614160463111',
    projectId: 'quiz-app-pdp',
    storageBucket: 'quiz-app-pdp.appspot.com',
    iosBundleId: 'com.example.quizAppPdp',
  );
}
